import java.util.UUID;

public abstract class Character {
    // ATRIBUTOS
    private final String id;     // Autogenerated
    private String name;
    private int hp;
    private boolean isAlive;

    // CONSTRUCTOR
    public Character(String name, int hp) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.hp = hp;
        this.isAlive = true;
    }

    // SETTERS Y GETTERS

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getHp() {
        return hp;
    }
    public boolean getIsAlive() {
        return isAlive;
    }

    public void setName(String name) {
        this.name = name;
    }
    public void setHp(int hp) {
        this.hp = hp;
    }
    public void setAlive(boolean alive) {
        isAlive = alive;
    }

    @Override
    public String toString() {
//        if (this.hp <= 0) {
//            this.hp = 0;
//            this.isAlive = false;
        return "";
    }
}