import java.util.UUID;

public abstract class Character implements Attacker{
    // ATRIBUTOS
    private final String id;     // Autogenerated
    private String name;
    private int hp;
    private boolean isAlive;

    // CONSTRUCTOR
    public Character(String name, int hp) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.hp = hp;
        this.isAlive = true;
    }

    public Character(String name) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.isAlive = true;
    }

    // SETTERS Y GETTERS

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getHp() {
        return hp;
    }
    public boolean getIsAlive() {
        return isAlive;
    }

    public void setName(String name) {
        this.name = name;
    }
    public void setHp(int hp) {
        this.hp = hp;
        this.isAlive = hp > 0;
    }
    public void setAlive(boolean alive) {
        isAlive = alive;
    }

    @Override
    public String toString() {
        return "Character{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", hp=" + hp +
                ", isAlive=" + isAlive +
                '}';
    }
}
